spring:
  liquibase:
    change-log: dbrate.changelog/changelog.xml

logging:
  level:
    root: info
  file:
    name: logs/ExchageRate.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"